version: "3"

services:
  proxy:
    image: nginx:alpine
    container_name: rstcm_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - client
    networks:
      - front

  client:
    container_name: rstcm_client
    volumes:
      - .:/usr/src/app
    tty: True
    build: .
    networks:
      - front
    environment:
      - NODE_ENV=production

networks:
  front:
    driver: bridge
